aliyun-oss.endpoint: oss-cn-beijing.aliyuncs.com
aliyun-oss.access-key-id: LTAI5tKV1DUUsFHVX3oMsCvS
aliyun-oss.access-key-secret: mbKNbr2NzNYm15J7X3fA1KOyQuCBQp
aliyun-oss.bucket-name: huan-student
aliyun-oss.dir: test/
